vaadin.launch-browser=true
spring.application.name=POO3
# ==========================================
# Configurações de Conexão (PostgreSQL 15)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/petshop_erp
spring.datasource.username=postgres
spring.datasource.password=POO3_123
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# Configurações do JPA e Hibernate 6
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Atualiza o esquema do banco automaticamente na fase de desenvolvimento
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# Logs e Auditoria de Consultas
# ==========================================
# Exibe no console as consultas SQL geradas (útil para debugar JPQL e Criteria API)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Configurações de E-mail (Exemplo com Mailtrap)
# ==========================================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=1b53a02ad6e8e6
spring.mail.password=2902f9824d2c6c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true