apiVersion: v1
kind: ConfigMap
metadata:
  name: petshop-config
data:
  # O URL aponta para o serviço do Postgres que criaremos abaixo
  db-url: jdbc:postgresql://postgres-service:5432/petshop
  db-username: postgres